version: '3.1'

services:
  telegrambot:
    depends_on:
      - jrtb-db;
    build:
      context: .
    environment:
      - BOT_NAME = ${BOT_NAME}
      - BOT_TOKEN = ${BOT_TOKEN}
      - BOT_DB_USERNAME = ${BOT_DB_USERNAME}
      - BOT_DB_PASSWORD = ${BOT_DB_PASSWORD}
    restart: always
  jrtb-db:
    image: mysql:8.1
    restart: always
    container_name: dev-jrtb-db
    ports:
      - "3307:3306"
    expose:
      - "3307"
    environment:
      MYSQL_DATABASE: "dev_jrtb_db"
      MYSQL_USER: ${BOT_DB_USERNAME}
      MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: "root"