version: '3.1'

services:
  jrtb-db:
    image: mysql:8.1
    restart: always
    container_name: dev-jrtb-db
    ports:
        - "3307:3306"
    expose:
        - "3307"
    environment:
      MYSQL_DATABASE: "dev_jrtb_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "userpassword"
      MYSQL_ROOT_PASSWORD: "root"


